### PR TITLE
Fixes #5 doesnt work with browserify 13.0.1

### LINKED ISSUE #5: What is the status of this project?
#Hi this is a great idea but Im struggling to get this to work with the latest browserify.What version of browserify is v1.0.3  compatible with. I have tried browserify v6.2.0 as listed in package.json, but still having problems.

### PR DESCRIPTION
**Pull request by the4thamigo-uk**
In browserify v13.0.1 the call contains this + 7 additional arguments. However the ternery operator selects for 3 arguments : 

```
(function e(t, n, r) {
    function s(o, u) {
        if (!n[o]) {
            if (!t[o]) {
                var a = typeof require == "function" && require;
                if (!u && a) return a(o, !0);
                if (i) return i(o, !0);
                var f = new Error("Cannot find module '" + o + "'");
                throw f.code = "MODULE_NOT_FOUND", f
            }
            var l = n[o] = {
                exports: {}
            };
            t[o][0].call(l.exports, function(e) {
                var n = t[o][1][e];
                return s(n ? n : e)
            }, l, l.exports, e, t, n, r)     // <---------------------------------HERE
        }
        return n[o].exports
    }
```

Note that we need to get the key for the t[] map, which is the integer 'o' passed to the call to s(o,u). This is arguments.callee.caller in the call to the following function :
```
    1: [function(require, module, exports) {
        var $0 = arguments.length === 7 ? arguments.callee.caller : arguments.callee.caller.caller,
            $1 = (arguments.length === 7 ? arguments.callee.caller : arguments.callee.caller.caller).arguments[0];
        var fresh = require('fresh-require');
        CTX = function(name) {
            this.name = name;
            this.OBJ1 = fresh('./obj1.js', $0, $1) || require('./obj1.js');
            this.OBJ1.ctx = this;
            this.OBJ2 = fresh('./obj2.js', $0, $1) || require('./obj2.js');
            this.OBJ2.ctx = this;
        };
        module.exports = CTX;
    }, 
```

### CODE REVIEW

**Comment by the4thamigo-uk** [comment]
Note this is a minimal fix, but Im not sure there is a need anymore for the ternery operator?
